import os

# ACCESS_KEY_ID = 'AKIA4ZEOEZRCDLW5LY6Q'
# ACCESS_SECRET_KEY = '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'
# AWS_STORAGE_BUCKET_NAME = 'rekovideo'
# AWS_S3_REGION_NAME = 'ap-south-1'

ACCESS_KEY_ID = os.environ['ACCESS_KEY_ID']
ACCESS_SECRET_KEY = os.environ['ACCESS_SECRET_KEY']
AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']
AWS_S3_REGION_NAME = os.environ['AWS_S3_REGION_NAME']

