import os

ACCESS_KEY_ID = os.environ['ACCESS_KEY_ID']
ACCESS_SECRET_KEY = os.environ['ACCESS_SECRET_KEY']
AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']
AWS_S3_REGION_NAME = os.environ['AWS_S3_REGION_NAME']
GRAMMARBOT_API_KEY = os.environ['GRAMMARBOT_API_KEY']
GRAMMARBOT_URI = os.environ['GRAMMARBOT_URI']


